from typing import TYPE_CHECKING, Any, Union

if TYPE_CHECKING:
    # 1. Define the base class for what SR and var() actually return
    class Expression:
        def expand(self) -> 'Expression': ...
        def simplify(self) -> 'Expression': ...
        def substitute(self, *args, **kwargs) -> 'Expression': ...
        
        # Overload math operators so your linter knows doing math on
        # Expressions results in another Expression
        def __add__(self, other: Any) -> 'Expression': ...
        def __radd__(self, other: Any) -> 'Expression': ...
        def __sub__(self, other: Any) -> 'Expression': ...
        def __rsub__(self, other: Any) -> 'Expression': ...
        def __mul__(self, other: Any) -> 'Expression': ...
        def __rmul__(self, other: Any) -> 'Expression': ...
        def __truediv__(self, other: Any) -> 'Expression': ...
        def __rtruediv__(self, other: Any) -> 'Expression': ...
        def __pow__(self, other: Any) -> 'Expression': ...

    # 2. Define SR. In Sage, SR is an instance of a SymbolicRing class,
    # but for typing purposes, typing it as a function that returns an Expression is easiest.
    def SR(value: Union[int, float, str, Expression]) -> Expression: ...

    # 3. Update your existing stubs to return Expression instead of Any where applicable
    def var(*args, **kwargs) -> Expression: ...
    def function(*args, **kwargs) -> Any: ...  # Functions are technically different (Callable symbolic expressions)
    def diff(expr: Expression, *args, **kwargs) -> Expression: ...
    def desolve(*args, **kwargs) -> Expression: ...
    def partial_fraction(*args, **kwargs) -> Expression: ...
    def latex(*args, **kwargs) -> str: ...       # Latex usually returns a string
    def display(*args, **kwargs) -> None: ...    # Display returns nothing
    def integral(*args, **kwargs) -> Expression: ...
    def exp(*args, **kwargs) -> Expression: ...
    def show(*args, **kwargs) -> None: ...
    
    class Math: ...