from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    def var(*args, **kwargs) -> Any: ...
    def function(*args, **kwargs) -> Any: ...
    def diff(*args, **kwargs) -> Any: ...
    def desolve(*args, **kwargs) -> Any: ...
    def partial_fraction(*args, **kwargs) -> Any: ...
    def latex(*args, **kwargs) -> Any: ...
    def display(*args, **kwargs) -> Any: ...
    def integral(*args, **kwargs) -> Any: ...
    def exp(*args, **kwargs) -> Any: ...
    def show(*args, **kwargs) -> Any: ...
    class Math: ...
